[앨런] 자동차 경주게임 미션 제출합니다.
Woohan-TDD/java-racingcar pull request #1
Opened 2020-06-20 15:45 UTC by khb1109

안녕하십니까. 앨런입니다.

자동차 경주미션을 진행했습니다.
Depth를 최대한 줄이려고 노력했고, 객체지향적으로 짜보려고 노력했습니다.
또 원시값을 최대한 포장하려고 했는데 좀 힘들어서,,, ㅠㅠ 꼭 필요한 부분만 포장했습니다.
테스트커버리지는 도메인 80% 진행했고, 이퀄스, 해시코드, Getter를 제외하고 모두 진행했습니다.

감사합니다.

2020-06-21 01:04 UTC, ksy90101 requested changes
안녕하세요 앨런 방학 시작 부터 너무 달리시네요~ ㅎㅎ
앨런의 성격만큼 화끈하게 TDD를 한 모습이 보여 코드 보는데 즐거웠습니다~
몇가지 피드백을 남겼으니 확인후 다시 리뷰 요청 해주세요~
(테스트 코드에서는 그닥 건들지 않았어요. 다음 요청때 자세하게 보겠습니다~)
그리고 아래에도 간단하게 몇가지 더 해볼께요!

1. 도메인 패키지 분리
도메인 패키지에 모두 다 들어가있어요 예외는 예외대로, Car관련된것은 Car패키지에 정리 해보시는걸 추천합니다!

2. 지금 @Override 클래스랑 Getter의 순서가 어떤 클래스는 Overried가 위에 있고, 어느 클래스는 아래에 있고 통일성이 없네요.. ㅎㅎ 이제 팀 프로젝트를 진행하는 만큼 순서를 정확히 해주시는걸 추천합니다!

3. 상수필드와 일반 필드를 개행을 줘서 구분해주시는걸 추천합니다~

4. 인자에도 final을 붙혀보시는거 어떨까요!?

2020-06-21 01:04 UTC, ksy90101 commented on README.md
> +    - 2 ~ 10명 사이의 이름을 입력받아야 한다.
11명 이상의 이름을 입력해도 실행이 되네요!?

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/Main.java
> +	private static final Logger logger = Logger.getLogger("logger");
Logger 미쳤다.... 👍

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/domain/Cars.java
> +	private final NumberStrategy numberStrategy;
상수필드와 일반 필드는 한칸을 띄어서 구분해주면 어떨까요!?

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/domain/InvalidRacingCountException.java
> +	}
기본 생성자는 왜 만드셨는지 물어봐도 될까요!?

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/domain/InvalidRacingCountException.java
> +	}
```suggestion
	public InvalidRacingCountException(int amount) {
		super(MESSAGE + amount);
	}
```
이렇게 할 수 있을거 같은데 어떻게 생각하시나요!?

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/domain/Name.java
> +	public Name(final String name) {
어디에는 인자에 final이 붙어있고, 어디에는 안붙어 있네요.
최대한 final을 붙여 보는게 어떨까요!>

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/domain/RacingNameException.java
> +	}
기본 생성자가 있는 이유가 있을까요!?

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/domain/RacingNameException.java
> +	}
여기도 위에 피드백과 동일하게 변경할 수 잇을꺼 같아요!

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/view/OutputView.java
> +	private static final java.lang.String GAGE = "-";
여기만 java.lang.String인 이유가 있나요?

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/view/OutputView.java
> +			.mapToObj(x -> GAGE)
여기서 x가 뭔가요!? 명시적인 이름을 적어주는게 어떨까요!?

2020-06-21 01:04 UTC, ksy90101 commented on src/test/java/racingcar/domain/RacingGameManagerTest.java
> +		Car brown = CarProvider.create("brown", 3);
왜 jun과 CU는..... ㅠㅠ

2020-06-21 01:04 UTC, ksy90101 commented on src/test/java/racingcar/domain/CarProvider.java
> +	}
이거 테스트에 있어요... 뭔가요!?

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/domain/Cars.java
> +
이펙티브 자바 아이템 3. 인스턴스화를 막으려거든 private 생성자를 사용하라

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/domain/Car.java
> +
이펙티브 자바 아이템 3. 인스턴스화를 막으려거든 private 생성자를 사용하라

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/domain/Cars.java
> +		return cars;
Unmodified로 묶어보시는거 어떨까요!?

2020-06-21 01:04 UTC, ksy90101 commented on src/test/java/racingcar/domain/CarsTest.java
> +	void doRacing() {
테스트가 깨지네요... 확인부탁드려요!

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/Main.java
> +			System.out.println("잘못된 입력입니다.");
logger를 쓰셨는데, 굳이 System.out.prIntln을 쓰신 이유가 있나요?

2020-06-21 01:04 UTC, ksy90101 commented on src/main/java/racingcar/Main.java
> +			System.out.println("오류가 발생했습니다.");
logger를 쓰셨는데, 굳이 System.out.prIntln을 쓰신 이유가 있나요?

2020-06-21 01:04 UTC, ksy90101 commented on src/test/java/racingcar/domain/RacingCountTest.java
> +			.isInstanceOf(InvalidRacingCountException.class);
정확성을 위해 hasMessage도 추가해보시는걸 추천합니다~

2020-06-21 01:40 UTC, KS-KIM reviewed
안녕하세요, 앨런. 잘 작성해 주셨네요.

간단한 피드백 남겼으니 확인하시고 궁금하신 점 있으시면 DM 주세요:)

2020-06-21 01:40 UTC, KS-KIM commented on src/main/java/racingcar/domain/Car.java
> +	private static final int ASCENDING_CONDITION = 5;
상수와 필드 변수 사이에 한 칸 띄는건 어떨까요?

2020-06-21 01:40 UTC, KS-KIM commented on src/main/java/racingcar/domain/Car.java
> +		this(name, 0);
의미가 있는 상수를 사용해봅시다 :)

2020-06-21 01:40 UTC, KS-KIM commented on src/main/java/racingcar/domain/Car.java
> +		if (numberStrategy.createValue() >= ASCENDING_CONDITION) {
요구사항이 변경되어 자동차마다 다른 조건으로 이동 여부를 판단한다면 이 클래스를 재활용 할 수 있을까요?

2020-06-21 01:40 UTC, KS-KIM commented on src/main/java/racingcar/domain/Cars.java
> +			.orElseThrow(() -> new IllegalStateException("최대 값을 찾을 수 없습니다."));
최대값을 구하는 로직을 메서드 추출로 분리할 수 있을 것 같아요:)

2020-06-21 01:40 UTC, KS-KIM commented on src/main/java/racingcar/domain/Car.java
> +		return Integer.compare(this.position, other.position);
`isSamePosition`에서 인자의 null체크를 했는데, 여기서는 하지 않은 이유가 있으신가요?

2020-06-21 01:40 UTC, KS-KIM commented on src/main/java/racingcar/domain/Cars.java
> +	public void doRacing() {
`race`라는 네이밍은 어떨까요?

2020-06-21 01:49 UTC, KS-KIM commented on src/main/java/racingcar/domain/Car.java
> +		Objects.requireNonNull(other);
`requireNonNull(Object o, String message)`를 사용하여 예외에 메시지를 담아보는건 어떨까요?

2020-06-21 05:41 UTC, khb1109 commented on README.md
> +    - 2 ~ 10명 사이의 이름을 입력받아야 한다.
앗 수정했습니다..

2020-06-21 05:44 UTC, khb1109 commented on src/main/java/racingcar/domain/Cars.java
> +	private final NumberStrategy numberStrategy;
이런 컨벤션이 있었군요. 적용했습니다.

2020-06-21 05:45 UTC, khb1109 commented on src/main/java/racingcar/domain/InvalidRacingCountException.java
> +	}
추후에 기본 메서드으로도 Exception을 호출할 수 있으니 만들었습니다.
삭제하는게 나을까요? 일단은 남겨놓겠습니다.

2020-06-21 05:48 UTC, khb1109 commented on src/main/java/racingcar/domain/InvalidRacingCountException.java
> +	}
그럼 이 클래스는 그럼 MESSAGE만 뱉겠는데요..?
좀 더 범용적으로 사용하려면 직접 메시지를 넣어주는게 않을까요?

2020-06-21 05:50 UTC, khb1109 commented on src/main/java/racingcar/domain/Name.java
> +	public Name(final String name) {
Name쪽에만 인자에 final이 들어가고 있는데, 평소 잘 붙이지 않아서 전부 빼는쪽으로 가겠습니다.
final이 정말 불변을 만들어주지않는다고 생각됩니다. 도움을 주지만요. 
그래서 IDE에서 밑줄이 나오는걸 피하려고 하고 있습니다.

2020-06-21 05:52 UTC, khb1109 commented on src/main/java/racingcar/view/OutputView.java
> +	private static final java.lang.String GAGE = "-";
변경했습니다.

2020-06-21 05:53 UTC, khb1109 commented on src/test/java/racingcar/domain/RacingGameManagerTest.java
> +		Car brown = CarProvider.create("brown", 3);
면허가 없으실까요?ㅎㅎ

2020-06-21 05:53 UTC, khb1109 commented on src/test/java/racingcar/domain/CarProvider.java
> +	}
테스트코드에서 Car를 만들기 편하게 만들어주는 클래스입니다!

2020-06-21 05:54 UTC, khb1109 commented on src/test/java/racingcar/domain/CarsTest.java
> +	void doRacing() {
변경했습니다!

2020-06-21 05:55 UTC, khb1109 commented on src/main/java/racingcar/Main.java
> +			System.out.println("잘못된 입력입니다.");
서버와 클라이언트에게 주는 메시지를 나눈다는 느낌으로 했습니다.
클라이언트에게는 추상화된 메시지를 주고, 서버의 메시지는 Looger로 상세하게 메시지받도록했습니다.

2020-06-21 05:59 UTC, khb1109 commented on src/main/java/racingcar/domain/Car.java
> +		this(name, 0);
0이라는 값에서 초기값이라고 어느정도 인지할 수 있지 않을까요?
문자보다 숫자로 나타나는게 직관적이라고 생각됩니다.

2020-06-21 06:00 UTC, khb1109 commented on src/main/java/racingcar/domain/Car.java
> +		if (numberStrategy.createValue() >= ASCENDING_CONDITION) {
알트의 피드백은 해당 **조건**도 인터페이스로 분리하라는 말씀일까요?

2020-06-21 06:01 UTC, khb1109 commented on src/main/java/racingcar/domain/Cars.java
> +			.orElseThrow(() -> new IllegalStateException("최대 값을 찾을 수 없습니다."));
가독성이 더 좋아보이네요! 감사합니다.

2020-06-21 06:02 UTC, khb1109 commented on src/main/java/racingcar/domain/Car.java
> +		return Integer.compare(this.position, other.position);
여기도 검사를 해주는게 좋겠군요..!

2020-06-21 06:03 UTC, khb1109 commented on src/main/java/racingcar/domain/Cars.java
> +	public void doRacing() {
더 명확하네요!

2020-06-21 06:06 UTC, khb1109 commented on src/main/java/racingcar/domain/Car.java
> +		Objects.requireNonNull(other);
맞습니다...! 다음 미션부터 적용해봐도 될까요..?ㅎㅎ

2020-06-21 06:11 UTC, ksy90101 commented on src/main/java/racingcar/domain/InvalidRacingCountException.java
> +	}
사용하지 않는다면 삭제하는게 좋을꺼 같아요... ㅎㅎ

2020-06-21 06:31 UTC, ksy90101 approved these changes
앨런 고생 많았어요. 열심히 하는 모습 좋습니다.
로또 때도 코드 기대할께요~

2020-06-21 06:31 UTC, ksy90101 commented on src/main/java/racingcar/domain/RacingGameManager.java
> +import racingcar.domain.car.car_info.Name;
패키지명이 car.car_info 뭔가 중복이네요
car_info를 info로 변경해보는걸 추천합니다!

2020-06-21 06:31 UTC, ksy90101 commented on src/main/java/racingcar/domain/car/car_info/RacingNameException.java
>  public class RacingNameException extends RuntimeException {
예외는 예외끼리 모아 놓는 것이 좋을거 같아요 ㅎㅎ

2020-06-21 06:31 UTC, ksy90101 commented on src/main/java/racingcar/domain/car/Car.java
> +	private int position;
position을 포장해보시는걸 추천합니다.

`규칙 3: 원시값과 문자열의 포장`

2020-06-22 08:43 UTC, KS-KIM approved these changes

2020-06-22 11:53 UTC, khb1109 commented on src/main/java/racingcar/domain/RacingGameManager.java
> +import racingcar.domain.car.car_info.Name;
더 자연스럽군요!!

2020-06-22 12:07 UTC, khb1109 commented on src/main/java/racingcar/domain/car/car_info/RacingNameException.java
>  public class RacingNameException extends RuntimeException {
저는 패키지레벨로 나누면서 해당 패키지에 두는걸 선호하는데요.
해당 패키지레벨에 이런 Exception이 있구나! 확인할 수도 있고, 코드를 수정할 때 Exception 패키지에 모아놓으면 불필요한 Exception을 또 만들 수도 있다고 생각합니다.

2020-06-22 15:51 UTC, ksy90101 commented on src/main/java/racingcar/domain/car/car_info/RacingNameException.java
>  public class RacingNameException extends RuntimeException {
https://stackoverflow.com/questions/825281/should-exceptions-be-placed-in-a-separate-package
https://stackoverflow.com/questions/33480666/java-custom-exceptions-package-convention
앨런이 맞군요 ㅎㅎ

2020-06-25 08:21 UTC, merged